#!/bin/sh /etc/rc.common

. /lib/functions.sh

if [ ! -f "/etc/config/gl_ble_hw" ]; then
    touch "/etc/config/gl_ble_hw"
fi

board=$(board_name)

case "$board" in
        *ar300m*)
                model=ar300m
                ;;
        *ar750s*)
                model=ar750s
                ;;
        *e750*)
                model=e750
                ;;
        *x750*)
                model=x750
                ;;
        *x300b*)
                model=x300b
                ;;
        *xe300*)
                model=xe300
                ;;
        *x1200*)
                model=x1200
                ;;
        *s200*)
                model=s200
                ;;
        *x3000*)
                model=x3000
                ;;
        *)
                model=$board
                ;;
esac
echo $model

uci set gl_ble_hw.model=$model
uci commit gl_ble_hw